### PR TITLE
Removed ()

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by neonichu** [comment]
Thanks for this great contribution!

**Comment by KrauseFx** [comment]
Making the world a better place

**Comment by KrauseFx** [comment]
Getting all the internet points

**Comment by neonichu** [comment]
As you have now made a 🔑 contribution to this project, I'd like to add you to the team of maintainers. I can send you the CLA today if you wish to participate in this great effort.

**Comment by KrauseFx** [comment]
Yes please!

**Pull request merged**
